# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 'canopy-devops-vmss-d2asv5-platform'

steps:
- task: UseNode@1
  inputs:
    version: '^22'
  displayName: 'Install Node.js'

- task: npmAuthenticate@0
  displayName: 'Authenticate to Azure Artifacts feed'
  inputs:
    workingFile: .npmrc

- script: |
    set -e
    curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain stable
    echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
  displayName: "Install rust (*nix)"
  condition: not(eq(variables['Agent.OS'], 'Windows_NT'))

- script: cargo install wasm-pack
  displayName: 'Install wasm-pack'

- script: wasm-pack build --target=web
  displayName: 'Build'

- script: wasm-pack publish
  displayName: 'Publish'