[package]
name = "rbf_rust"
version = "0.1.2"
edition = "2021"

[profile.release]
lto = true
opt-level = 3


[lib]
crate-type = ["cdylib"]

[dependencies]
nalgebra = "0"
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.4"
